# Generated by Django 3.2.10 on 2022-02-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('datetime_start', models.DateTimeField(verbose_name='Начало события')),
                ('datetime_end', models.DateTimeField(verbose_name='Конец события')),
            ],
        ),
    ]
